import Head from 'next/head'
import { Auth } from '../src/components/Auth'
import { Container, Main } from '../src/ui/styled'
import dynamic from 'next/dynamic'
import { Bg } from './../src/ui/styled'

const Stars = dynamic(() => import('../src/components/Stars'), {
  ssr: false
})

export default function Home() {
  return (
    <Bg>
      <Container>
        <Head>
          <title>My-Prod</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main>
          <Stars />
          <Auth />
        </Main>
      </Container>
    </Bg>
  )
}
