import Head from 'next/head'
import { Auth } from '../src/components/Auth'
import { Container, Main } from '../src/ui/styled'

export default function Home() {

  return (
    <Container>
      <Head>
        <title>My-Prod</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Auth />
      </Main>
    </Container>
  )
}
