import Head from 'next/head'
import { Auth } from '../src/components/Auth'
import { NavBar } from '../src/components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>My-Prod</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Auth />
      </main>
    </div>
  )
}
